Localized properties hints, label of shema's field
Squidex/squidex pull request #599
Opened 2020-11-25 03:17 UTC by dborovsky

Localized properties hints, label of shema's field

2020-11-25 13:00 UTC, SebastianStehle requested changes
It goes into the right direction :)

2020-11-25 13:59 UTC, dborovsky commented on backend/src/Squidex.Domain.Apps.Core.Model/Schemas/NamedElementPropertiesBase.cs
> +                if (DefaultValuesLabel.TryGetValue(CultureInfo.CurrentUICulture.ToString(), out var current))
What you mean "Perhaps we can move this code to LocalizedValue"?

2020-11-25 14:02 UTC, SebastianStehle commented on backend/src/Squidex.Domain.Apps.Core.Model/Schemas/NamedElementPropertiesBase.cs
> +                if (DefaultValuesLabel.TryGetValue(CultureInfo.CurrentUICulture.ToString(), out var current))
It is a common behavior, we can add a method to LocalizedValue class.

2020-11-26 10:22 UTC, dborovsky commented on frontend/app/shared/services/schemas.service.ts
>          public readonly label?: string,
Do you mean implement getter in class FieldPropertiesDto? 
`this.localizedLabel[currentLanguage] ` - how better get user's current language? I don't see any method for this. I only see implementation in profile-menu-component as `public language = this.uiOptions.get('more.culture');`

2020-11-26 10:27 UTC, SebastianStehle commented on frontend/app/shared/services/schemas.service.ts
>          public readonly label?: string,
I think we need a pipe for that...so we can inject the uiOptions

2021-01-25 20:02 UTC, closed without merging