Feature/add array builder
Squidex/squidex pull request #709
Opened 2021-05-26 14:54 UTC by sebestyn168

Hello,

This feature alllows to further script template in order to enable creating ArrayFields
The idea is to describe array in schema as follow
```
            SchemaBuilder.Create("TEST")
		.AddArray("Array TEST", f => f
			.Label("Label TEST")
			.Hints("Hints TEST")
			.Localizable()
			//.Disabled()
			//.Required()
			.AddString("String TEST", a => a
				.Required())
			.AddBoolean("Boolean TEST", a => a
				.Hints("Boolean hints TEST"))
			.AddDateTime("DateTime TEST", a => a
				.Hints("DateTime Hints TEST"))
			.AddNumber("Number TEST", a => a
				.Hints("Number Hints TEST"))
			.AddAssets("Logo TEST", a => a
				.MustBeImage()
				.Hints("Logo Hints TEST")))
			.Build();
```

2021-05-26 21:37 UTC, SebastianStehle requested changes
Thank you very much. Just some minor change-requests.

2021-05-26 21:37 UTC, SebastianStehle commented on backend/src/Squidex.Domain.Apps.Entities/Apps/Templates/Builders/ArrayFieldBuilder.cs
> +        public new ArrayFieldBuilder Label(string? label) => base.Label(label) as ArrayFieldBuilder;
Two things:

1. Can this not be solved with a generic base class: `ArrayFieldBuilder : FieldBuilder<ArrayFieldBuilder>`
2. Please do not use expression members, not a fan.

2021-05-26 21:37 UTC, SebastianStehle commented on backend/src/Squidex.Domain.Apps.Entities/Apps/Templates/Builders/ArrayFieldBuilder.cs
> +        {
Please make the formatting of this method consistent (similar to AddJson)

2021-05-27 10:25 UTC, sebestyn168 commented
Hello,
I've added commits according to your requests.
I've ran some tests for the `ArrayFieldBuilder : FieldBuilder<T>` update and it works.

2021-05-27 10:53 UTC, merged